[package]
name = "puniyu_component_help"
version = "0.4.0"
description = "puniyu help component"
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
include = [
    "Cargo.toml",
    "src/**",
    "fonts/**"
]
[dependencies]
puniyu_skia.workspace = true
thiserror.workspace = true
image = "0.25"
resvg = "0.45"