name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      help: ${{ steps.release-please.outputs['packages/puniyu_component_help--release_created'] }}
      node: ${{ steps.release-please.outputs['node--release_created'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json


  publish-to-crates:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: ${{ needs.release.outputs.help }}
    steps:
      - name: 检出代码
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: puniyu-component

      - name: 设置apt 包
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1
        with:
          packages: pkg-config libssl-dev libfontconfig-dev

      - name: 发布component-help
        if: needs.release.outputs.help
        run: |
          cargo publish --package puniyu_component_help
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: ${{ needs.release.outputs.node }}
    steps:
      - name: 检出代码
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
          run_install: true

      - name: 构建node
        run: |
          pnpm install
          bun build
        working-directory: node

      - name: 发布node
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./node
          access: public
