name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      help: ${{ steps.release-please.outputs['packages/puniyu_component_help--release_created'] }}
      napi: ${{ steps.release-please.outputs['napi--release_created'] }}
      napi_tag_name: ${{ steps.release-please.outputs['napi--tag_name'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json


  publish-lib:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: ${{ needs.release.outputs.help }}
    steps:
      - name: 检出代码
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 rust
        uses: puniyu/setup-rust@main
        with:
          target: ${{ matrix.platform.target }}
          save-cache: true
          prefix-key: puniyu-component

      - name: 设置apt 包
        uses: awalsh128/cache-apt-pkgs-action@2c09a5e66da6c8016428a2172bd76e5e4f14bb17 # v1
        with:
          packages: pkg-config libssl-dev libfontconfig-dev

      - name: 发布component-help
        if: needs.release.outputs.help
        run: |
          cargo publish --package puniyu_component_help
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}


  build:
    needs: release
    if: needs.release.outputs.napi
    uses: ./.github/workflows/build.yml

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载npm包
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: "npm-package"
          path: napi

      - name: 下载构建产物
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          pattern: component-node*
          path: napi/artifacts

      - name: 设置pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.24.0

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: napi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            napi/artifacts/component-node-*/*.node
          tag_name: ${{ needs.release.outputs.napi_tag_name }}

